import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { ClerkProvider } from '@clerk/nextjs'
import { MenuItem } from "@/utils/types"
import { Container } from "@/components/ui/atoms/Container"
import { HomeHeader } from "@/components/ui/organisms/HomeHeader"
import { ToastContainer } from "@/components/ui/molecules/Toast"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'TerraFarming',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Bookings', href: '/bookings' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={inter.className}>
            <HomeHeader menuItems={MENUITEMS} />
            <Container>{children}</Container>
            <ToastContainer />
          </body>
      </html>
    </ClerkProvider>
  )
}